<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>

		<AssemblyName>Queue.Messaging.Abstractions</AssemblyName>
		<RootNamespace>Queue.Messaging.Abstractions</RootNamespace>

		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>true</IsPackable>
		<PackageId>Queue.Messaging.Abstractions</PackageId>
		<Version>0.1.0-preview.1</Version>
		<Authors>Queue Messaging</Authors>

		<Description>
			Broker-independent messaging contracts, envelopes,
			publishing abstractions and retry scheduling contracts.
		</Description>

		<PackageTags>
			messaging;abstractions;queue;event-driven
		</PackageTags>

		<PackageRequireLicenseAcceptance>
			false
		</PackageRequireLicenseAcceptance>

		<GeneratePackageOnBuild>
			false
		</GeneratePackageOnBuild>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference
		  Include="Microsoft.NETFramework.ReferenceAssemblies.net48"
		  PrivateAssets="all" />
	</ItemGroup>

</Project>