<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Messaging.RabbitMq\**" />
    <EmbeddedResource Remove="Messaging.RabbitMq\**" />
    <None Remove="Messaging.RabbitMq\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RabbitMq\Rabbit.Messaging.Abstractions\Rabbit.Messaging.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
