<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Messaging.RabbitMq\**" />
    <EmbeddedResource Remove="Messaging.RabbitMq\**" />
    <None Remove="Messaging.RabbitMq\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentProcessing.Contracts\DocumentProcessing.Contracts.csproj" />
    <ProjectReference Include="..\DocumentProcessing.Core\DocumentProcessing.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
