<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DocumentProcessing.Contracts\DocumentProcessing.Contracts.csproj" />
    <ProjectReference Include="..\DocumentProcessing.Core\DocumentProcessing.Core.csproj" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Messaging.RabbitMq\" />
    <Folder Include="Connection\" />
  </ItemGroup>
</Project>
