<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Testcontainers.RabbitMq" />
		<PackageReference Include="xunit" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\src\DocumentProcessing.Contracts\DocumentProcessing.Contracts.csproj" />
		<ProjectReference Include="..\src\DocumentProcessing.Core\DocumentProcessing.Core.csproj" />
		<ProjectReference Include="..\src\DocumentProcessing.Messaging.RabbitMq\DocumentProcessing.Messaging.RabbitMq.csproj" />
	</ItemGroup>

</Project>