<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\DocumentProcessing.Contracts\DocumentProcessing.Contracts.csproj" />
		<ProjectReference Include="..\DocumentProcessing.Core\DocumentProcessing.Core.csproj" />
	</ItemGroup>
</Project>
